### ISSUE TITLE
Add a section at the beginning about who is this book for

### ISSUE THREAD

**Issue by alcueca** [cairo-book/cairo-book#1017]
I think that you have at least three potential personas reading this book:
1. Developers which aren't interested in smart contracts.
2. Developers who don't know about smart contracts, and take Cairo as their first smart contract language.
3. Developers who are familiar about smart contracts, and want to start using Cairo to code them.

A section at the beginning ("Who is this book for") would help the reader situate themselves. You could have some guidelines on how to read the book according to the persona.
1. Read up to chapter 12
2. Read the whole thing front to back
3. Read 1, 2, the first half of 3, 4 and 7. Then read 12 and onwards, and go back as necessary to fill in gaps.

**Comment by akintewe** [comment]
Hello can i be assigned this task please @alcueca, i really love to contribute :)

**Comment by enitrat** [comment]
What do you think of having this as part of the Introduction chapter ?
This page is a bit outdated now and could benefit from a complete revamp. I think it would be a good fit there.
