### ISSUE TITLE
Dead link in Upgradeable Contracts section

### ISSUE THREAD

**Issue by NikitaMishin** [cairo-book/cairo-book#1018]
chapter https://book.cairo-lang.org/ch16-03-upgradeability.html

For more information, please refer to the [OpenZeppelin docs API reference](https://docs.openzeppelin.com/contracts-cairo/0.9.0/api/upgrades). 

-> it leads to not found

**Comment by Iwueseiter** [comment]
Can I look this up and fix it? @NikitaMishin

**Comment by Iwueseiter** [comment]
Will get to work.
