### ISSUE TITLE
ci: cache dependencies

### ISSUE THREAD

**Issue by enitrat** [cairo-book/cairo-book#1038]
Improve the current CI jobs to cache the dependencies installed:
- asdf (with scarb & starknet-foundry)
- rust
- pnpm and the node modules
- the mdbook dependencies built from source.

Instead of re-installing / building these dependencies on each workflow run, we can just restore a previous time, reducing CI workflow times.

**Comment by 0xdevcollins** [comment]
I'd be happy to do this.

**Comment by mimisavage** [comment]
Can I tackle this one?

**Comment by 0xdevcollins** [comment]
Thanks @enitrat
