### ISSUE TITLE
Gas

### ISSUE THREAD

**Issue by enitrat** [cairo-book/cairo-book#1070]

**Comment by faytey** [comment]
Hello @enitrat I'd love to work on this gas builtin

**Comment by enitrat** [comment]
Hi, after further research it seems that the Gas "Builtin" is not really a built-in but just a type for an implicit argument used to track gas usage throughout function execution. Thus i will be closing this

**Comment by faytey** [comment]
> Hi, after further research it seems that the Gas "Builtin" is not really a built-in but just a type for an implicit argument used to track gas usage throughout function execution. Thus i will be closing this

Yes you are right sir
