### ISSUE TITLE
Advanced Cairo: Supertraits - Require a functionnality in another trait

### ISSUE THREAD

**Issue by enitrat** [cairo-book/cairo-book#121]
Describe how one can require a trait to depend on another trait.
Rust equivalent: https://doc.rust-lang.org/book/ch19-03-advanced-traits.html#using-supertraits-to-require-one-traits-functionality-within-another-trait

This section can demonstrate this feature by using an example requiring the implementation of PrintTrait.
Example snippet associated:

```
use debug::PrintTrait;

trait C {
    fn foo();
}

impl B of C {
    fn foo() {
        'foo'.print();
    }
}

trait A<impl B: C> {
    fn bar();
}

impl CompositeImpl of A<B> {
    fn bar() {
        B::foo();
        'bar'.print();
    }
}

fn main() {
    A::bar();
}

```

Estimated time: 1hr

**Comment by wraitii** [comment]
Note that there is currently a bug in Cairo (https://github.com/starkware-libs/cairo/issues/2995) that means this won't work with generic implementations.

I'm also fairly sure this should be writable as `impl CompositeImpl of A {` without specifying `<B>`, but it's crashing as well.

**Comment by martriay** [comment]
do we need intermediate impls or can we just do

```cairo

trait A {
...
}

trait B<A> {
...
}

trait C<B> {
...
}
```

**Comment by remybar** [comment]
I would propose this example which is similar to the one in Rust doc:
```rust
use core::fmt::{Display, Formatter, Error};

#[derive(Copy, Drop)]
struct Point {
    x: u8,
    y: u8
}

impl PointDisplay of Display<Point> {
    fn fmt(self: @Point, ref f: Formatter) -> Result<(), Error> {
        let str: ByteArray = format!("({}, {})", *self.x, *self.y);
        f.buffer.append(@str);
        Result::Ok(())
    }
}

trait OutlinePrint<T, +Display<T>> {
    fn outline_print(self: @T);
}

impl PointOutlinePrint of OutlinePrint<Point> {
    fn outline_print(self: @Point) {
        println!("**********\n* {}\n**********", *self);
    }   
}

fn main() {
    let p = Point { x: 1, y: 3};
    p.outline_print();
}
```

Where do you want to add this section ? There is a quite similar section in "Generic Data Types" which explains how to constraint generic types of functions to implement a specific behaviour but I guess it would be better to add this new section in "Traits in Cairo".

What do you think ?

**Comment by enitrat** [comment]
this is using the trait bound syntax. In Cairo generic traits are always linked to a type so I don't think the concept can be applied correctly

**Comment by remybar** [comment]
> this is using the trait bound syntax. In Cairo generic traits are always linked to a type so I don't think the concept can be applied correctly

Yes, I would say that as a trait implementation is always linked to a type, you can only constraint the type to  have implemented a trait, right ? As explained for functions in the chapter "Generic Data Types".

In the code snippet you gave as example, for me there is no link between `CompositeImpl` and `B`, and I think you can just write the same example as:

```rust
trait C {
    fn foo();
}

impl B of C {
    fn foo() {
        println!("foo");
    }
}

trait A {
    fn bar();
}

impl CompositeImpl of A {
    fn bar() {
        B::foo();
        println!("bar");
    }
}
```

So yes, I'm not sure we can contraint a trait to depend on another trait, but I have still a lot of things to learn in Cairo 😅

**Comment by enitrat** [comment]
At the time I opened this issue I'm not sure trait bounds were already something 😄 maybe we should close this

**Comment by remybar** [comment]
> At the time I opened this issue I'm not sure trait bounds were already something 😄 maybe we should close this

Yep, we can close it and create another task in the future if this kind of concept appear in a future Cairo version :)
