### ISSUE TITLE
feat: Introduction to Smart Contracts

### ISSUE THREAD

**Issue by enitrat** [cairo-book/cairo-book#142]
The Cairo Book must be beginner friendly - we do not expect prior knowledge of blockchain programming languages, and we should provide some explanation about what smart contracts are, what they can be used for, and why they're not the same on Starknet as on Ethereum (mostly, why are we using Cairo ?)

This part might be overlapping with the [Starknet Book](https://book.starknet.io/chapter_2/index.html) - But I think it's still great to have a succinct introduction in our book.

Estimated time: 2 to 3 hours

**Comment by 0xEniotna** [comment]
Can I take this one big boss ?
