### ISSUE TITLE
Advanced Cairo: Smart pointers in Cairo

### ISSUE THREAD

**Issue by enitrat** [cairo-book/cairo-book#236]
This section will explain what smart pointers are (the `Box<T>` type), where and how to use them.
We will also cover the `Nullable<T>` type.

estimated time: 2 to 3 hours

**Comment by faytey** [comment]
Can I try working on this

**Comment by enitrat** [comment]
You can try, but before please explain what your approach will be. This is advanced Cairo level

**Comment by faytey** [comment]
Oh Okay, so I'd make much more research on pointers and generic types, I have some understanding on memory pointers from solidity, I'm guessing it's in line with this issue, then how to call and use generic types properly. What do you think?

**Comment by enitrat** [comment]
I think the best way is to first start by a higher level introduction about smart pointers (vaguely similar to rust), talk about their importance for safety purposes when compiling to sierra/casm, 

And then dive deeper by compiling Cairo0 code using pointers to CASM, then do the equivalent code in Cairo 1 with Boxes/Nullable to understand how the memory is managed

2-3h is a bit underestimated but I think this is probably in the 4-6hours range so that you have time to research and build meaningful examples

**Comment by enitrat** [comment]
> Ok great, can you kindly point me to resources available that I can use?

Not sure there are any, the goal of the Cairo Book is to BE the resource 🫡

**Comment by faytey** [comment]
okay then

**Comment by faytey** [comment]
Hi @enitrat , this is really taking me sometime to come up with, can I be pointed to engineers who have adequate knowledge on this, or discussions from the ecosystem around this.

**Comment by enitrat** [comment]
Hi @faytey, this is a complicated task and I cannot redirect you to anyone that has the adequate knowledge apart from the creators of Cairo themselves. I think this is doable by reading the code of the compiler directly, but this is a difficult task (it was marked as `difficulty: hard` - I would advise that you try to pick an easier one

**Comment by faytey** [comment]
Ouch, okay I'd drop it, thanks

**Comment by enitrat** [comment]
@wraitii 👀 you fancy some more bookwriting?
