### ISSUE TITLE
Advanced Cairo: Inlining in Cairo

### ISSUE THREAD

**Issue by enitrat** [cairo-book/cairo-book#268]
Ressources talking about inlining in Rust:

- https://matklad.github.io/2021/07/09/inline-in-rust.html
- https://doc.rust-lang.org/nightly/reference/attributes/codegen.html?highlight=inline#the-inline-attribute

In Cairo, it's a bit different - you basically avoid using a `function_call` libfunc by directly injecting the sierra code in the caller function's context. 

Inlining can, in some cases, improve performances, and should be considered when it makes sense. 
In this part, we will outline the mechanisms of inlining in Cairo, provide an in-depth example with a very basic comparison between inlined / not-inlined functions at the Sierra level / CASM level, and provide insights on when to / not to use inlining.

est. time: 3 to 4 hours

**Comment by rkdud007** [comment]
Is this mentioning about `#[inline(always)]` syntax ?

**Comment by enitrat** [comment]
Yes you can read https://medium.com/nethermind-eth/under-the-hood-of-cairo-1-0-exploring-sierra-1220f6dbcf9 to learn a bit more about what happens. Then I suggest you read directly from the compiler source code to understand better the different types of inlining and what they do
