### ISSUE TITLE
feat: syscalls

### ISSUE THREAD

**Issue by enitrat** [cairo-book/cairo-book#269]
List the syscalls available on Starknet, what they do, and how to call them. You will write explanatory text for each syscall and provide a **meaningful** example
This will be an appendix.
est. 1 hour

**Comment by 0xEniotna** [comment]
🙋‍♂️🙋‍♂️🙋‍♂️

**Comment by TedZy829** [comment]
hi, regarding this task, it is to add a new appendix section consisting syscalls from starknet which can be found from this link right: https://docs.starknet.io/documentation/architecture_and_concepts/Smart_Contracts/system-calls-cairo1/

**Comment by enitrat** [comment]
Hey @TedZy829 thanks for your interest in this issue. I am not sure it is still relevant, given that the documentation page that you linked didn't exist when this issue was created. I do not see a lot of value add if we replicate it in the book, this is pretty much what I had in mind at the time

**Comment by TedZy829** [comment]
i see, thank you for the feedback!

**Comment by enitrat** [comment]
Hey @TedZy829 after discussing the idea, I think it's nice to have it in the book, even though it's replicated from the page I linked. If you want to handle this, the idea would be to copy the page, add credits redirecting to it on top, and modify the format so that it's nice with mdbook

**Comment by glihm** [comment]
+1, could be nice to have a summary of syscall here, and like this we can add some additional content later if some edge-cases are detected or interesting to know.

**Comment by TedZy829** [comment]
Noted, thanks for the feedback! I will most probably take this issue and work on it soon!

**Comment by enitrat** [comment]
Great!

**Comment by julienbrs** [comment]
Hi @TedZy829 , are you still working on this or can I take it?

**Comment by TedZy829** [comment]
> Hi @TedZy829 , are you still working on this or can I take it?

No I am not, feel free to take it!

**Comment by julienbrs** [comment]
Thanks! Will take this one @enitrat please
