### ISSUE TITLE
Add a naming convention section

### ISSUE THREAD

**Issue by robertkodra** [cairo-book/cairo-book#348]
Might be helpful to add a section/subsection for the naming convention.

https://github.com/starkware-libs/cairo/blob/1a28a015c490442b688160b2635a55763c4f832b/docs/reference/src/components/cairo/modules/language_constructs/pages/naming-conventions.adoc#L17

Let me know if we want this and I can work on it.

**Comment by enitrat** [comment]
@robertkodra Good idea; however there is no community consensus about conventions yet. Would you like to propose one on the community forum?

**Comment by robertkodra** [comment]
Great, will do that, thanks!

**Comment by enitrat** [comment]
@robertkodra any updates? I think the ecosystem would really benefit from a SNIP around naming conventions - especially given that the naming of component `impls` and `embeddable_as` is super bug prone.

**Comment by Enenche23** [comment]
Very interested in this project, would love to be part of it

**Comment by TAdev0** [comment]
@robertkodra any update?

**Comment by enitrat** [comment]
I think this should be a SNIP

**Comment by robertkodra** [comment]
@TAdev0 no, feel free to take it, but as @enitrat said it needs to be a SNIP and propose it to the community.

**Comment by TAdev0** [comment]
I close this issue as there is no convention for now. As soon as a SNIP is proposed and accepted for this, i'll open an issue so that we can integrate it in the book
