### ISSUE TITLE
Dead Links in chapter 12.6

### ISSUE THREAD

**Issue by CountryCousin** [cairo-book/cairo-book#418]
1. account abstraction link is `not found` in chapter 12.6.
2. links to setting up katana and starkli are `not found` in chapter 12.6.

**Comment by CyndieKamau** [comment]
Hey @CountryCousin for setting up Katana and Starkli they have been recently updated in Starknet Book.

Installing Katana, Starkli -> https://book.starknet.io/ch02-01-basic-installation.html

Intro to Katana, Starkli -> https://book.starknet.io/ch02-02-starkli-scarb-katana.html

Quick guide to Katana -> https://book.starknet.io/ch02-04-katana.html

As for account abstraction, that's what I've been working on. The changes are currently under review! I'm sure they'll be updated in Cairo book eventually. Cheers!!
