### ISSUE TITLE
Add a subsection about enum storage in the Storage chapter

### ISSUE THREAD

**Issue by enitrat** [cairo-book/cairo-book#419]
It shouldn't take longer than 1 hour for an intermediate cairo dev

**Comment by OkoliEvans** [comment]
Let me make some research on this and work on it @enitrat

**Comment by enitrat** [comment]
Sure!

**Comment by enitrat** [comment]
Just FYI enums can be stored by deriving starknet::Store on them, but what is interesting is to give information about the generated storage layout and how variants are stored/retrieved.

**Comment by OkoliEvans** [comment]
Okay

**Comment by OkoliEvans** [comment]
I have submitted a PR on this, here: https://github.com/cairo-book/cairo-book/pull/438
@enitrat
