### ISSUE TITLE
feat: question mark operator

### ISSUE THREAD

**Issue by milancermak** [cairo-book/cairo-book#435]
Add information about the question mark operator, where and how it works, etc. 🙏

**Comment by enitrat** [comment]
It's already here https://book.cairo-lang.org/ch10-02-recoverable-errors.html#the--operator

Do you have something specific in mind?

**Comment by milancermak** [comment]
Huh, missed it there, thanks!

It's missing from [Operators](https://book.cairo-lang.org/appendix-02-operators-and-symbols.html) section though.
