### ISSUE TITLE
Suggestion: Add last change page footer

### ISSUE THREAD

**Issue by julio4** [cairo-book/cairo-book#446]
Cairo is a rapidly evolving language, and this Cairo Book is maintained by numerous contributors. This leads to frequent updates with no versioning, making it challenging to track new changes.

I suggest adding a "Last update" note with a commit link at the bottom of all pages. This will allow users to easily identify modified or newly created pages without leaving the book.

**Comment by julio4** [comment]
It seems to fetch only the last commit, however checkout should fetch the whole history as specified [here](https://github.com/cairo-book/cairo-book/blob/11481e21995b4517292c1818a2d263d35d3fe2ff/.github/workflows/mdbook.yml#L36)
I did the same setup in Starknet By Example today and didn't encountered this problem, I'll investigate...

**Comment by enitrat** [comment]
I don't get it, what's wrong?
