### ISSUE TITLE
Advanced Cairo: Component dependencies

### ISSUE THREAD

**Issue by enitrat** [cairo-book/cairo-book#452]
All there is to know about how to make component depend on other component, and craft contracts with multiple intricates components.

As this is not a pattern that is familiar for a lot of users coming from POO language, we should write about the reason behind this design choice as much as possible.

**Comment by enitrat** [comment]
@julio4 wanna take it?

**Comment by julio4** [comment]
Yes I can!

**Comment by TAdev0** [comment]
#620

**Comment by TAdev0** [comment]
@enitrat  I close this issue as completed
