### ISSUE TITLE
feat: 2.4.0 

### ISSUE THREAD

**Issue by enitrat** [cairo-book/cairo-book#454]
## Cairo

- [x] refactor `#[should_panic(expected: 'error')]` to use double quotes instead of single (less confusing)
- [x] match on felt252 continuous from 0 and on values
- [x] Felt252Dict<bool> fixed
- [ ] Dicts of non-copy nullable type possible: access items using `entry` rather than `get` #421
- [x] Prelude editions - Add info about this in the first chapter where we dissect `Scarb.toml`
    Currently 2 editions exist: 2023_01 (default) and 2023_10.
- [x] Remove `#[available_gas(X)]` attributes on test functions (simplify)
- [x] `assert_eq!` for testing - in tests only
- [x] `assert!` and `panic!` macros to panic with a format string instead of a single felt252 non-dynamic value
- [x] `print!` and `println!` macros - replace all existing uses of `val.print()` by `println!("{}", val)`
- [x] format string (bytearray) creation with `format!` macro
- [x] `write!` and `writeln!` - TBD
- [x] Display and Debug traits

**Comment by enitrat** [comment]
Hi @faytey can you link me some of your previous work?

**Comment by faytey** [comment]
okay do you mean personal projects or contributions i've made because all is on my repo github.com/faytey

**Comment by TAdev0** [comment]
@enitrat  i'm available to work on some of 2.4 features if needed :)
