### ISSUE TITLE
migration from `#[external(v0)]` to `#[abi(embed_v0)]`

### ISSUE THREAD

**Issue by enitrat** [cairo-book/cairo-book#461]
Convert all `impl` block marked as `#[external(v0)]` to either `#[abi(embed_v0)]` or `#[abi(per_item)]`, depending on what's the most appropriate one to use (rule of thumb: explicit interface -> `#[abi(embed_v0)]`, generated trait -> `#[abi(per_item)]` )

**Comment by faytey** [comment]
So just for clearer context, any particular file or folder to work on

**Comment by enitrat** [comment]
@faytey any updates?

**Comment by TAdev0** [comment]
@faytey  i'm available to work on this issue tomorrow if you are not available these days.

**Comment by faytey** [comment]
@enitrat so sorry my pc screen got broken, still fixing it, @TAdev0 please go ahead so I don’t delay much more, I currently can’t push what I’ve done so you have to start afresh, @enitrat so sorry once again
