### ISSUE TITLE
Some traits from corelib don't need to be explicitly imported anymore.

### ISSUE THREAD

**Issue by TAdev0** [cairo-book/cairo-book#470]
I recently realised that with recent versions of cairo compiler,  a lot of traits that needed to be imported dont need it anymore.

For example, `use array::ArrayTrait;` or `use dict::Felt252Dict;` are now superflu, and arrays can be created and manipulated with associated methods without any issue.

This does only applies for a few corelib traits. For example (from cairobook) :
```
use poseidon::PoseidonTrait;
use poseidon::poseidon_hash_span;
use hash::{HashStateTrait, HashStateExTrait};
```
removing the first line makes it impossible to use `new` method of Poseidon type.
The seconde line is optional, as it could be bypassed using directly `poseidon::poseidon_hash_span()`.

I suggest to modify sections in cairo book where manually imports are not necessary.

For example, in dictionnaries section : 
"The first thing we do is import Felt252DictTrait which brings to scope all the methods we need to interact with the dictionary" should be modified to explain that the compiler does the work for us now.

I don't really which version of the compiler introduced these improvements,  2.3.1 or before. Probably that it was step by step on multiple upgrades?

**Comment by enitrat** [comment]
Actually - I was going to create an issue about the opposite: make all imports explicit. 

Now, the compiler exposes 2 different versions of the prelude: 
- One general version, with _a lot_ of stuff that is made available in the prelude (edition `2023_01`)
- A restricted version, which requires importing content from the prelude manually with `use core::path::to:object` (edition `2023_10`

The thing is: Creating a new project with `scarb new project` creates a project with the restricted prelude. I didn't necessarily understand everything about _why_ we should use this newer, smaller version instead, but I think it's related to the fact that this allows for users to opt-in newer versions that might have breaking changes, while keeping retroactive compatibility possible

**Comment by TAdev0** [comment]
Interesting ! Your interpretation seems totally logic. Let's be more explicit then, and import everything manually from prelude in cairo programs :)

**Comment by enitrat** [comment]
#471
