### ISSUE TITLE
feat: add Option methods description and examples in 6.1 section

### ISSUE THREAD

**Issue by TAdev0** [cairo-book/cairo-book#478]
Option enum are well described in Cairo Book, but there is no mention about Option methods : `expect` , `unwrap`, `is_some` and `is_none` . 

`Unwrap` is briefly mentioned in an example in 6.2 section.

I think it could be helpful to describe Option methods and how they work exactly, with short examples.

**Comment by enitrat** [comment]
This would be great for the docs of the corelib but not adapted for the content of the book, imo.

The problem is just that there is no corelib reference. But if you open the source code, it's actually well documented
