### ISSUE TITLE
feat: update 11.2 Macros

### ISSUE THREAD

**Issue by TAdev0** [cairo-book/cairo-book#482]
While recently working with `println!` (cairo macro) and `selector!` (starknet-specific macro), i noticed that Macros section in Cairo Book only describes `array!` and `consteval_int!` macros.  
I guess there are some other inline macros but i didn't find where to see all available macros. 

I think Macros section should add `println!` macro short description (which is now used everywhere in the book instead of  print() function of core::debug::PrintTrait). 
`selector!` could also be described (as mentioned in #425), though it is specific to starknet contracts.

If there is a way to find all available macros, i would be happy to describe all (or some) of them in the book as well.

**Comment by TAdev0** [comment]
update : 

A few macros are currently available : 
- `array!` since 2.1.0, already well described
- `consteval_int!` , i can't find info about the release
- `selector!` since 2.2.0, should be added in Macros section. This macro is actually available for any cairo program, whether inside or outside starknet contracts. It returns `sn_keccak` of the function's big endian name
- Since 2.4.0, `print` and `println` macros, should probably also be added in macros section? though already described in 1.2. . Also, `panic!` , `assert!` and `assertEq!` macros, allowing to have more than 31 chars for the panic error. Adding these would probably require introduction of the new `Formatter` struct available corelib, and its usage, including `write!` and `format!` macros.

**Comment by enitrat** [comment]
Hey @TAdev0, you can take the new macros if you want!

**Comment by enitrat** [comment]
Also, I think these contents should be succintly referenced in the `macro` section, but more importantly they should be integrated in the corpus where it makes sense to introduce them. You can (and should) use the Rust book as a base for this - I think you should stay fairly close to it as long as the content makes sense when writing about Cairo.

Here's my proposal:
- Adapt the existing chapters of the book with the content of the Rust book listed below (e.g. `println!` in the intro chapter, `panic!` in the panic chapter, etc
- Move the description of `array!` to the Array chapter
- In the Macros chapter, replace the explanations by a link to the chapter section where these macros are introduced.

References:
[println!](https://book.cairo-lang.org/ch01-02-hello-world.html?highlight=println!#anatomy-of-a-cairo-program)
[assert!](https://doc.rust-lang.org/book/ch11-01-writing-tests.html?highlight=assert!#checking-results-with-the-assert-macro)
[panic!](https://doc.rust-lang.org/book/ch09-01-unrecoverable-errors-with-panic.html)
[assert_eq!](https://doc.rust-lang.org/book/ch11-01-writing-tests.html?highlight=assert!#testing-equality-with-the-assert_eq-and-assert_ne-macros)

For `write!`, `writeln`, `format!`, I think we can have a succint description in the Macros chapter for now. Once strings are better supported by the language (I don't know what's the plan for this - for now they're just `ByteArray`, we will move them to the String chapter

**Comment by TAdev0** [comment]
Hi @enitrat thanks for your answer, I will do that !
