### ISSUE TITLE
Missing example for `pedersen` function usage with 2 felts

### ISSUE THREAD

**Issue by TAdev0** [cairo-book/cairo-book#495]
While doing Security Challenges Factory for Starknet (https://starknet-challenges.vercel.app/) , i've been facing an issue related to `pedersen` hash function. 

In one of their CTFs, i was supposed to calculate the pedersen hash of two `felt252`.  I first used the method described in cairo book : 
```
    let hash = PedersenTrait::new(0).update_with(struct_to_hash).finalize();
```
As my solution didn't work, i searched in corelib and found that pedersen hash of 2 `felt252` is simply calculated as follows : 
```
            let hash = core::pedersen::pedersen(param1, param2);
```
It worked this way. I guess that using the `struct_to_hash` with `update_with` method doesn't return the same hash, even with a struct containing 2 felts, as each element of the struct is hashed one after the other, using hash state accumulators.  This means that in my example, the hash will be the result of `pedersen(pedersen(0, param1), param2)`, instead of `pedersen(param1, param2)`.

I'm not sure this is relevant as `pedersen` seems to be less and less used, with `poseidon` being more STARK friendly.  But I think this is a missing detail that might be important. What do you think @enitrat ?

**Comment by enitrat** [comment]
yes please fix it!

**Comment by TAdev0** [comment]
@enitrat 

update : 
Also, it seems it is still possible to compute the right hash, by doing : 
```
    let hash = PedersenTrait::new(param1).update_with(param2).finalize();
 ```
now i feel it is not useful to integrate `core::pedersen::pedersen(param1, param2)` ?

**Comment by enitrat** [comment]
Ah yes we should always use the high level trait. The initial value is the default state of the hash, which is the first value to hash

**Comment by TAdev0** [comment]
yes ! 
If you want , i can just add one or two lines to explain how to hash 2 felt252 using the high level trait :)
