### ISSUE TITLE
Update example Ch02-05-Control Flow

### ISSUE THREAD

**Issue by LeandroCarvajal** [cairo-book/cairo-book#504]
The examples show the code:
```
$ cairo-run main.cairo
[DEBUG]	condition was false
```
Is it possible to open a Pr by updating the code with the following code?:
```
scarb cairo-run --available-gas=20000000
[DEBUG]	condition was false and number = 3
```

I also suggest applying it in the two adjacent examples within Control Flow,
https://book.cairo-lang.org/ch02-05-control-flow.html

**Comment by enitrat** [comment]
Hi, yes please open a pr

**Comment by LeandroCarvajal** [comment]
Hi! already made the changes mentioned in the following PR,
https://github.com/cairo-book/cairo-book/pull/506#issue-2072874892
Thans
