### ISSUE TITLE
Event Docs Typo ?

### ISSUE THREAD

**Issue by 0xDegenDeveloper** [cairo-book/cairo-book#507]
I was reading the Cairo events docs and noticed the output of the example event was stated to be: `keys = [sn_keccak("StoredName"),user]` and `data = [address]`.

Curious what happened to the `name: felt252` member mentioned here: 

```
    #[derive(Drop, starknet::Event)]
    struct StoredName {
        #[key]
        user: ContractAddress,
        name: felt252 // * here
    }
```

Should the paragraph say: `keys = [sn_keccak("StoredName"),user]` and `data = [name]` instead ? Or am I misunderstanding something ? 

Noticed right above [here](https://book.cairo-lang.org/ch99-01-03-03-contract-events.html#emitting-events), if this is not a typo would someone mind breaking down where `name` goes ?

**Comment by enitrat** [comment]
Yeah I think it used to be address before but a change in the example has changed it to name and the change was not reflected there!

**Comment by 0xDegenDeveloper** [comment]
Gotcha thanks !

**Comment by enitrat** [comment]
you can PR it if you want :)
