### ISSUE TITLE
Version mdbook

### ISSUE THREAD

**Issue by SimplementeCao** [cairo-book/cairo-book#510]
Hi @enitrat. I have a doubt, is the version being used in the mdbook the `0.4.28`? I make this query because when modifications are made in the .po are not reflected in main, but if when tested locally, since by default installs the most current version, in this case the `0.4.36`.
Thanks

**Comment by enitrat** [comment]
In the lockfile it says

```
[[package]]
name = "mdbook"
version = "0.4.31"
```

What is the problem exactly?

**Comment by LeandroCarvajal** [comment]
This is a versioning problem that occurs in several books that use mdbook, when corrections or translations are made locally, they show up perfectly, but not in the main when a merge is made. It might be worth considering adding this to the readme for future contributions.

**Comment by enitrat** [comment]
Do you know how to fix it? Should we pin a specific version?

**Comment by TAdev0** [comment]
@SimplementeCao  any update about this issue? is there anything we should do?

**Comment by SimplementeCao** [comment]
Hi @TAdev0 the best thing to do is to add that version of book in the readme, I did some research and in other mdbooks they solved that problem using `0.4.31` in local. As long as the mdbook version of the repository is not updated. Do you have any suggestions?

**Comment by TAdev0** [comment]
ok so currently the book uses `0.4.28`. Can we just update to the most recent one?
