### ISSUE TITLE
maintain: Chapter 1

### ISSUE THREAD

**Issue by enitrat** [cairo-book/cairo-book#532]
## Getting Started
- [x] Add a brief introduction to the content covered in this chapter

## Installation
- [x] Rewrite parts of the installation section (add a few lines), to put forward the flow of installation with asdf instead of the direct Scarb installation. This is extremely practical when working on multiple projects with different versions. Keep a link to the Scarb docs to install normally.
- [x] update Scarb –version output to 2.5.0 for now

## Hello World
- [x] remove “and a directory for the ‘’Hello, World!” project within the cairo_projects directory” as it will be created with scarb just after
- [x] reorder the Scarb Note after the command line instructions
- [x] Navigate to your **cairo_projects** directory
- [x] “--vcs” flag should be “--no-vcs”
- [x] the name and the version of Scarb to use => the name of the package and the version of Scarb to use
- [x] modify the Scarb.toml file as edition is now by default “edition = 2023_11” 
- [x] Remove references to `scarb test` - out of scope for now
- [x] Add ‘’scarb cairo-run’’ in the recap of commands learned
- [x]  Remove scripts and `scarb run` references

**Comment by TAdev0** [comment]
@enitrat  i added "Remove scripts and scarb run references".
just like tests, there is a reference to scripts at the end but its out of scope for now

**Comment by TAdev0** [comment]
and for  my `scarb.toml`, there was one `scarb.toml` mention in italic instead of inline code, i corrected that

**Comment by enitrat** [comment]
> and for my

i think references to files and folder are meant to be in italic

**Comment by TAdev0** [comment]
ok i will modify
