### ISSUE TITLE
Building Advanced Contracts: randomness section

### ISSUE THREAD

**Issue by TAdev0** [cairo-book/cairo-book#554]
Create a subsection in "Building Advanced Contracts', providing a contract example requesting a random felt252 using pragma VRF  for some raffle game.

**Comment by okhaimie-dev** [comment]
@TAdev0 can you assign this to me. Thanks!

**Comment by enitrat** [comment]
@okhaimie-dev any updates?

**Comment by TAdev0** [comment]
@enitrat  we had a call yesterday with Okhai, i think a new PR should be pushed during this week
