### ISSUE TITLE
Maintain Chapter 9 Testing cairo programs

### ISSUE THREAD

**Issue by TAdev0** [cairo-book/cairo-book#566]
- [x]  Error Handling (10) should be moved just before Testing cairo programs (9), as `assert!` is widely used in testing chapter without being introduced 
- [x] 9-1: ‘’For now … on the function’’ should be removed as we explain the first line just after
- [ ] 9-1: #[cfg(test)] attribute never described in this section, we should do it , at least a small reference to the next section (testing organization) 
- [x] 9-1: In should_panic section, the last snippet of code is supposed to introduce a bug via swapping bodies but this is not done
- [ ] 9-1: print() call in benchmarking the gas usage example should be replaced by println!
- [ ] 9-2: Introduction phrase should be modified as public/private functions are now possible with pub attribute
- [ ] 9-2: `cfg(tests)` should be `cfg(test)`

**Comment by Joy-Adah** [comment]
Are these tasks still available?

**Comment by TAdev0** [comment]
@Joy-Adah  sorry no this is not available
