### ISSUE TITLE
Refactor: printing a struct with a custom trait

### ISSUE THREAD

**Issue by TAdev0** [cairo-book/cairo-book#576]
Chapter 5-2 needs a refactoring of the last section, where we use `print` to output the fields avec the Rectangle struct.
We should use macros instead.

**Comment by enitrat** [comment]
But we stlil want to keep the spirit of this chapter which is to add a functionality to a type by implementing with a trait

**Comment by enitrat** [comment]
Well that's actually redundant with the next section "Method Syntax" - we should just delete this imo

**Comment by TAdev0** [comment]
You are right, this is redundant, will remove it.
