### ISSUE TITLE
feat: Make Storage Packing section more digest

### ISSUE THREAD

**Issue by enitrat** [cairo-book/cairo-book#586]
This section is a bit hard to approach for a reader that's not very at ease with bit manipulation. 

We should have a small intro about the inner structure of an integer (bits), how we can combine multiple values inside a single bigger value, with schemas that help understand the process. Only after can we talk about it in the context of Starknet and storage optimizations. 

We can also illustrate the the packing / unpacking process from the example with schemas to, similar to the ones done in the Contract Storage section (using Excalidraw - but any tool of your choice would work)

**Comment by remybar** [comment]
FYI, I'm on it 👍
