### ISSUE TITLE
feat : 2.6.0

### ISSUE THREAD

**Issue by TAdev0** [cairo-book/cairo-book#596]
- [x] if - let expression
- [x] while let support.
- [x] assert_lt!, assert_le!, assert_ge!, assert_gt! in tests
- [x] underscore pattern in match on tuples (ie you can do `_ =>` instead of (_ , _) =>`
- [x] Support for complex consts (Non-Zero, struct, enum, fixed size arrays).
- [x] Change all ` loop { arr.pop_front ...} ` loops to `while let Option::Some` loops - except the ones used for the `loop` keyword explicitly
- [x] Const array type https://doc.rust-lang.org/book/ch03-02-data-types.html#the-array-type

**Comment by TAdev0** [comment]
https://github.com/starkware-libs/cairo/releases

**Comment by okhaimie-dev** [comment]
@TAdev0 @enitrat 

Seems v2.6.0 is no more a release candidate and out, can I make a PR to include 

- `if let`
- `while let`

to the chapter on [control flow](https://book.cairo-lang.org/ch02-05-control-flow.html#control-flow)?

**Comment by TAdev0** [comment]
Go ahead @okhaimie-dev  !

**Comment by enitrat** [comment]
relevant pages:

https://doc.rust-lang.org/stable/book/ch06-03-if-let.html

I could see both `if let` and `while let` fit in here

**Comment by okhaimie-dev** [comment]
@TAdev0 can you create a `ch06-03` file for this as eni suggested? I'd do it myself, but you asked me not to touch `SUMMARY.md` file to avoid conflicts.

I am going to get started writing on a throwaway branch while I wait for you to make the file addition.

**Comment by TAdev0** [comment]
@okhaimie-dev you can modify the summary file now no worries :) you can create the file

**Comment by TAdev0** [comment]
@enitrat  should we do a section about gas coupon?

**Comment by enitrat** [comment]
No
