### ISSUE TITLE
feat: update Cairo runner

### ISSUE THREAD

**Issue by kwkr** [cairo-book/cairo-book#599]
Are the code snippets only meant to be run locally or they are supposed to run online as well? Whenever I try to run them using https://book.cairo-lang.org, I get the error above.

**Comment by enitrat** [comment]
yeah we had to update the code examples to support the latest version (with prints), but we still need to update the code runner to the last version. cc @cryptonerdcn

**Comment by cryptonerdcn** [comment]
Will update it soon ser!

**Comment by kwkr** [comment]
Are there any plans to have a server that would handle running the code? From what I can see it's currently a separate WASM that needs to be prepared and redeployed. In the Rust Book I saw they have some server that's evaluating the code under `https://play.rust-lang.org/evaluate.json`. I can imagine something like this should be quite easy to do using `scarb` binaries and a bit more flexible when it comes to updating.

**Comment by enitrat** [comment]
In the future I'm thinking about having a dedicated playground with quizzes to do along reading the book.
I already know that https://cairovm.codes/ is doing this, and has some extra cool features associated. For the book I think having a WASMed version of Cairo deployed along is the best path to follow as everything is done client-side

**Comment by cryptonerdcn** [comment]
Sorry for the late, got sick last weekend, but will release a new version of wasm-cairo soon.

**Comment by enitrat** [comment]
@cryptonerdcn any update?

**Comment by cryptonerdcn** [comment]
@enitrat Sorry for late. I got an allergic reaction to pollen allergy(a very common disease in Japan's spring) these weeks but am recovering now.
Still WIP.

**Comment by Enenche23** [comment]
would like to join this team

**Comment by cryptonerdcn** [comment]
https://github.com/cairo-book/cairo-book/pull/728
Finished.
