### ISSUE TITLE
Describe `selector!` macro

### ISSUE THREAD

**Issue by TAdev0** [cairo-book/cairo-book#643]
`selector!` macro computes sn_keccak and is very useful in contracts. For now, we can see this macro in one contract example, but without explanation.

https://book.cairo-lang.org/ch14-02-contract-dispatchers-library-dispatchers-and-system-calls.html?highlight=selector!#using-low-level-syscalls

Find the appropriate place and add informations to describe this macro.

**Comment by JimmyFate** [comment]
Hey :)
I can give it a try

**Comment by TAdev0** [comment]
Sure go ahead @JimmyFate  , thanks!
