### ISSUE TITLE
error: no such command: `cairo-run`

### ISSUE THREAD

**Issue by jney** [cairo-book/cairo-book#647]
Trying hello world [example from the book](https://book.cairo-lang.org/ch01-02-hello-world.html#building-a-scarb-project), I got:

```sh
❯ scarb cairo-run
error: no such command: `cairo-run`
```

current version

```sh
❯ scarb --version
scarb 2.5.4
cairo: 2.5.4 (https://crates.io/crates/cairo-lang-compiler/2.5.4)
sierra: 1.4.0
```

Did I miss some steps on install?

**Comment by enitrat** [comment]
it should work fine 🤔 Perhaps something wrong with your $PATH ?

**Comment by jney** [comment]
fyi I installed `scarb` using homebrew

**Comment by jney** [comment]
```
❯ brew install scarb
// ...

❯ scarb commands
Installed Commands:
add                   : Add dependencies to a Scarb.toml manifest file
build                 : Compile current project
cache                 : Manipulate packages cache
check                 : Analyze the current package and report errors, but don't build Sierra files
clean                 : Remove generated artifacts
commands              : List installed commands
fetch                 : Fetch dependencies of packages from the network
fmt                   : Format project files
init                  : Create a new Scarb package in existing directory
manifest-path         : Print path to current Scarb.toml file to standard output
metadata              : Output the resolved dependencies of a package, the concrete used versions including overrides, in machine-readable format
new                   : Create a new Scarb package at <PATH>
package               : Assemble the local package into a distributable tarball
publish               : Upload a package to the registry
remove                : Remove dependencies from a manifest file
run                   : Run arbitrary package scripts
test                  : Execute all unit and integration tests of a local package
update                : Update dependencies

❯ scarb --version
scarb 2.5.4
cairo: 2.5.4 (https://crates.io/crates/cairo-lang-compiler/2.5.4)
sierra: 1.4.0
```

**Comment by enitrat** [comment]
https://docs.swmansion.com/scarb/download.html

I don't see brew as a listed installation methods in the doc. I recommend following the steps in the book

**Comment by enitrat** [comment]
https://github.com/software-mansion/scarb

I'm not sure who is managing the brew version but you should open an issue there

**Comment by jney** [comment]
ok

**Comment by maciektr** [comment]
Hi!
As Eni has hinted, we have not authored, nor do we maintain the homebrew installation script. After quickly going through their code, it seems to me. that they indeed do erroneously omit all binaries apart from Scarb. My suggestion is to use the official installation methods from docs until we get it fixed with homebrew.

**Comment by chenrui333** [comment]
This should be an easy fix, I will address it now.

**Comment by chenrui333** [comment]
PR fix, https://github.com/Homebrew/homebrew-core/pull/165096

**Comment by chenrui333** [comment]
We shipped the change, should be good now.

**Comment by Hedwika** [comment]
I have the same problem, any suggestions pls?

> scarb --version
scarb 2.7.0-rc.0 (01e327bb3 2024-07-01)
cairo: 2.7.0-rc.0 (https://crates.io/crates/cairo-lang-compiler/2.7.0-rc.0)
sierra: 1.6.0

> scarb cairo-run
error: no such command: `cairo-run`
