### ISSUE TITLE
Add mdbook-quiz to allow revision quizzes after each chapter

### ISSUE THREAD

**Issue by kwkr** [cairo-book/cairo-book#658]
What do you think about adding some interactive questions using:
https://github.com/cognitive-engineering-lab/mdbook-quiz
after each chapter. I saw you already mentioned the idea and there is already a preprocessor available that could be tested out. I could take care of configuring it if needed.

**Comment by enitrat** [comment]
yes, that's a good idea. I noted this for later but if you want to start working on it feel free to!

**Comment by enitrat** [comment]
You can check https://rust-book.cs.brown.edu/ for inspiration. It's an enhanced version of the rust book with quizzes
