### ISSUE TITLE
feat: implement a preprocessor that injects error messages automatically after compilation

### ISSUE THREAD

**Issue by LeandroCarvajal** [cairo-book/cairo-book#661]
Hi @enitrat I have been running the example commands shown in the [Ch04-01](https://book.cairo-lang.org/ch04-01-what-is-ownership.html#destruction-with-a-side-effect-the-destruct-trait) and I see slightly different results:
```
error: Variable not dropped. Trait has no implementation in context: core::traits::Drop::<temp7::temp7::A>. Trait has no implementation in context: core::traits::Destruct::<temp7::temp7::A>.
 --> temp7.cairo:7:5
    A {
    ^*^
```
But currently it would look like this:
```
   Compiling helloworld v0.1.0 (/home/cairo/Scarb.toml)
error: Variable not dropped.
 --> /home/cairo/src/lib.cairo:6:5
    A { dict: Default::default() };
    ^****************************^
note: Trait has no implementation in context: core::traits::Drop::<helloworld::A>
note: Trait has no implementation in context: core::traits::Destruct::<helloworld::A>

error: could not compile `helloworld` due to previous error
Error: `scarb metadata` exited with error
```
I am using this version :
```
scarb 2.5.3 (46d5d5cea 2024-02-01)
cairo: 2.5.3 (https://crates.io/crates/cairo-lang-compiler/2.5.3)
sierra: 1.4.0
```
This is one, but while testing I saw that there are several that differ. Would it be convenient to update it? If so, I would like to work on it. 
Thks

**Comment by TAdev0** [comment]
hey @LeandroCarvajal  ! 
thanks for opening this issue. Indeed i just ran the first example and the error is slightly different than the one in the book and looks like this : 

```
error: Variable not dropped.
 --> .../src/lib.cairo:6:5
    A { dict: Default::default() };
    ^****************************^
note: Trait has no implementation in context: core::traits::Drop::<adder::A>
note: Trait has no implementation in context: core::traits::Destruct::<adder::A>
```

You can open a PR to make the change :)

**Comment by TAdev0** [comment]
There are also a few lines in this chapter like this : 

```
 let mut arr = ArrayTrait::<u128>::new();
 ```
 
 could you modify it for : 
 ```
 let mut arr:Array<u128> = array![];
```
?

**Comment by enitrat** [comment]
I think the best approach would be to compile the relevant and inject the message using a preprocessor. Otherwise we're going to have change the error messages every month

**Comment by LeandroCarvajal** [comment]
I agree, there are changes every month and it involves a lot of updates. If you think I can check what other crate could be added besides this one.

**Comment by TAdev0** [comment]
@LeandroCarvajal  would you like to work on implementating a preprocessor that injects error messages automatically after compiling?

**Comment by LeandroCarvajal** [comment]
@TAdev0 Yes! I would like to work on it

**Comment by enitrat** [comment]
@LeandroCarvajal any update? otherwise I might start this
