### ISSUE TITLE
feat: install scarb. first curl, second asdf

### ISSUE THREAD

**Issue by suiwater** [cairo-book/cairo-book#666]
https://docs.starknet.io/documentation/quick_start/environment_setup/#installing_scarb

https://github.com/cairo-book/cairo-book/blob/1a6fda11d197e20d318531ce861d6c943951b842/src/ch01-01-installation.md?plain=1#L48

asdf global scarb 2.5.3

```bash
$ scarb --version
scarb 2.5.4 (28dee92c8 2024-02-14)
cairo: 2.5.4 (https://crates.io/crates/cairo-lang-compiler/2.5.4)
sierra: 1.4.0
```
asdf install scarb  not working

asdf install
$ which scarb
$HOME/.asdf/shims/scarb

curl install
$ which scarb
$HOME/.local/bin/scarb

**Comment by enitrat** [comment]
I don't understand the issue

**Comment by suiwater** [comment]
As a beginner, follow the starkio documentation to install scarb, and then use asdf to install scarb. scarb was still installed in the starkio documentation, and using asdf to install did not work.

**Comment by enitrat** [comment]
I still don't understand what the issue is. The instructions in the book are correct.

**Comment by suiwater** [comment]
Mainly tell beginners to know how to view the installation directory of A.
Just close it if you don't need it.
