### ISSUE TITLE
Loop: no easy to understand

### ISSUE THREAD

**Issue by suiwater** [cairo-book/cairo-book#668]
fn find_value_iterative(mut arr: Span<felt252>, value: felt252) -> Option<usize> {
https://github.com/cairo-book/cairo-book/blob/1a6fda11d197e20d318531ce861d6c943951b842/listings/ch06-enums-and-pattern-matching/no_listing_03_enum_option/src/lib.cairo#L18

I  understand it.
The first time I saw it, I didn't understand
rust \} or \};

**Comment by TAdev0** [comment]
@suiwater  i'm not sure to understand what the issue is. This example seems correct?

**Comment by suiwater** [comment]
it is correct.

**Comment by suiwater** [comment]
this grammar is difficult to understand.
add  let result= loop { may better.
