### ISSUE TITLE
Highlight Storage etc in starknet contract is keyword

### ISSUE THREAD

**Issue by suiwater** [cairo-book/cairo-book#675]
struct Storage
enum Event
self: @ContractState etc.
 Storage Even ContractState etc is keyword

**Comment by enitrat** [comment]
I dont understand

**Comment by suiwater** [comment]
for example:
The first time I didn't even know that ContractState was a keyword, because ContractState is very similar to TContractState, so I emphasized that ContractState is a keyword. 
TContractState can be T(rust grammar).
ContractState can only be ContractState,  it cannot be any other name.

**Comment by enitrat** [comment]
Ok, I get it - thanks! @TAdev0 Indication to put in chapter 13 rework

**Comment by TAdev0** [comment]
Sure.
Thank you @suiwater

**Comment by Zeegaths** [comment]
@TAdev0 please assign me this

**Comment by TAdev0** [comment]
@Zeegaths  this issue has already been addressed , I close it. Thank you for your interest though
