### ISSUE TITLE
feat: enhance description of debugging / printing with Debug trait

### ISSUE THREAD

**Issue by enitrat** [cairo-book/cairo-book#718]
<img width="802" alt="image" src="https://github.com/cairo-book/cairo-book/assets/60658558/fbd4f7ac-54cf-49fc-8e36-921ef26ee6e3">

The chatbot cannot find this info efficiently in the book. Perhaps the difference between Display / Debug is not sufficiently explained nor easy to find

**Comment by TAdev0** [comment]
Will do it during the weekend
