### ISSUE TITLE
feat: Add Syscall for `sha256` in Syscall Appendix

### ISSUE THREAD

**Issue by TAdev0** [cairo-book/cairo-book#723]
Available once https://github.com/starkware-libs/cairo/pull/5348 is integrated in a release

**Comment by FriendlyLifeguard** [comment]
Hello, can I take this?

**Comment by TAdev0** [comment]
@FriendlyLifeguard  hi, sure! Just wait for the release please, I will comment again when it is available :)

**Comment by Jemiiah** [comment]
if FriendlyLifeguard isn't available, can this be assigned to me? @TAdev0

**Comment by TAdev0** [comment]
@Jemiiah thanks for you interest, but as you can see, @FriendlyLifeguard  is already assigned and will work on it as soon as this syscall is available in a new release.

**Comment by TAdev0** [comment]
@FriendlyLifeguard  issue unblocked, `sha256` syscall is included in 2.7
