### ISSUE TITLE
feat: use `output.txt` files to refer to command outputs

### ISSUE THREAD

**Issue by enitrat** [cairo-book/cairo-book#731]
- Identify all places where we manually insert the output of a command
- Create a `output.txt` at the root of the listing package
- first line should be `$ command-to-run`, e.g.: `$scarb build`

next, run the rust script
`cargo run --bin cairo-listings --output` to generate the outputs

Replace the hand-written output by a reference to the output file.

**Comment by princeibs** [comment]
Hi @enitrat, is this issue up for grabs?

**Comment by enitrat** [comment]
Yes, go ahead
