### ISSUE TITLE
Test running forever

### ISSUE THREAD

**Issue by gaetbout** [cairo-book/cairo-book#733]
In https://book.cairo-lang.org/ch10-01-how-to-write-tests.html
If hitting Run this code on a test it runs forever:
![image](https://github.com/cairo-book/cairo-book/assets/16206518/d3ac6685-3cfa-426b-9090-6c7d0d58ab16)

It shouldn't run forever and either tell it isn't possible or run the tests

**Comment by enitrat** [comment]
@cryptonerdcn is WASM-Cairo able to run cairo-tests?

**Comment by cryptonerdcn** [comment]
@gaetbout @enitrat WASM-Cairo still can’t run test. Can you open an issue to request this feature at here https://github.com/cryptonerdcn/wasm-cairo/issues ?
