### ISSUE TITLE
Appendix section appears twice in documentation

### ISSUE THREAD

**Issue by princeibs** [cairo-book/cairo-book#742]
I think this is a mistake. Appendix appears twice in the book.
<img width="271" alt="image" src="https://github.com/cairo-book/cairo-book/assets/64266194/665c74a4-ddf1-4fd1-b858-cb2260b986c1">

I could easily create a pr to move the appendix to the end of the book (to section 18)

**Comment by enitrat** [comment]
The idea was to have one Appendix for the Cairo part and one for the Starknet part. Do you think it's a bad idea to have this fragmentation?

**Comment by princeibs** [comment]
I think it is not clear to the reader which is for either Cairo or Starknet. I think using a separator like: Appendix(Cairo), Appendix(Starknet) will make it more obvious to readers @enitrat

**Comment by enitrat** [comment]
Ok, you can modify this if you think it is clearer

**Comment by manlikeHB** [comment]
Hi @enitrat, I would like to fix this issue if it's still available.

**Comment by TAdev0** [comment]
@princeibs  any update?

**Comment by princeibs** [comment]
Almost done with the PR. Sending it ASAP @TAdev0
