### ISSUE TITLE
Please elaborate more about the dictionary secion

### ISSUE THREAD

**Issue by huihzhao** [cairo-book/cairo-book#751]
The inner working mechanism is quite difficult to understand. For example, why dictionary squashing is needed, and what is the relationship btw the dictionary squashing and proof generation need to be clarified.

**Comment by enitrat** [comment]
Thank you for the feedback! I will think about how we can properly introduce this, I think it would require a complete section on the CairoVM to understand properly

**Comment by faytey** [comment]
@enitrat when you figure out and are ready to assign the issue, I would love to work on it, I also have some issues with dictionaries and would use the opportunity to solidify my understanding and usage of dictionaries. Thanks
