### ISSUE TITLE
bug: Changing language is not working

### ISSUE THREAD

**Issue by davmart2** [cairo-book/cairo-book#763]
When trying to change the language, an error appears.

[Document not found (404)](https://book.cairo-lang.org/#document-not-found-404)
This URL is invalid, sorry. Please use the navigation bar or search to continue.

**Comment by TAdev0** [comment]
Indeed, it doest work. @enitrat  might i be related to the recent upgrade of version of all packages in the cargo.toml file?

**Comment by Dprof-in-tech** [comment]
Hello @enitrat  i would love to work on this issue

**Comment by enitrat** [comment]
sure go ahead

**Comment by Dprof-in-tech** [comment]
Hello guys. So the error I can see is that a particular file
Can't be found but the file is available in the specified directory 

Could be a build issue. Still trying to figure it out

**Comment by Dprof-in-tech** [comment]
oh yeah i'm still working on it chief. Have an idea I want to try out and if it doesn't work, I would make sure to raise a question here

**Comment by Dprof-in-tech** [comment]
hi @TAdev0 i've tried changing the file path even duplicating it into the directory where it is needed but its absolutely to being read. This could be reassigned to someone else if there's anyone willing to pick it up, meanwhile I would keep trying to fix it and would send in a pr if I can

Thanks

**Comment by TAdev0** [comment]
This issue is free to grab :)

**Comment by addegbenga** [comment]
Can I work on this

**Comment by TAdev0** [comment]
sure @addegbenga  go ahead :)

As you can see on the website:

https://book.cairo-lang.org/

trying to change the langage from english to any other triggers a [Document not found (404) error

**Comment by CristopherAguilar10** [comment]
hello @TAdev0, @davmart2  , I wanted to make my first issue and this seems quite interesting to do, I think I have a possible solution and as there are no updates I would like to work on it.
