### ISSUE TITLE
doc: fix grammatical error in chapter 8.1

### ISSUE THREAD

**Issue by EjembiEmmanuel** [cairo-book/cairo-book#772]
@enitrat can you look at this, I think there is a grammatical error here. 

![image](https://github.com/cairo-book/cairo-book/assets/83036156/003d600f-d226-4646-938f-21f8b51c21dd)

**Comment by enitrat** [comment]
yes, you can fix to `does it`

**Comment by EjembiEmmanuel** [comment]
OK
