### ISSUE TITLE
dev: rework "Methods Without `self` Parameter"

### ISSUE THREAD

**Issue by enitrat** [cairo-book/cairo-book#786]
This specific paragraph in 5.3 method syntax is confusing and the title not adapted to what's actually being presented: _associated functions_, also known as _class methods_ in oop. typically, constructors returning an instance of the type`new()`.

Also: the `compare` method should not be in `RectangleImpl` as it should be an impl of `PartialEq` if we wanted to implement comparison.

**Comment by muheebyusufbaba1** [comment]
I'll like to work on this

**Comment by enitrat** [comment]
I prefer to keep it for experienced contributors
