### ISSUE TITLE
fix: integration tests section

### ISSUE THREAD

**Issue by enitrat** [cairo-book/cairo-book#789]
Now that scarb uses test targets from Scarb, we can have integration tests under `package_name/tests` instead of `package_name/src/tests/integration_tests`. Adapt the section accordingly. https://book.cairo-lang.org/ch10-02-test-organization.html#integration-tests

**Comment by kateberryd** [comment]
Hi @enitrat I would love to work on this

**Comment by mubarak23** [comment]
@enitrat i will like to work on this, kindly assign

**Comment by mubarak23** [comment]
@enitrat if i get you correctly this is where most of the code from the rust book will be implemented right 

[https://github.com/cairo-book/cairo-book/tree/main/listings/ch10-testing-cairo-programs/no_listing_09_integration_test/src/tests](https://github.com/cairo-book/cairo-book/tree/main/listings/ch10-testing-cairo-programs/no_listing_09_integration_test/src/tests)

**Comment by mubarak23** [comment]
> yes, this is the package where you define the cairo code, and you refer to it in the corpus using include macros (as done for other listings)

Good, can you refer me to where corpus was used in the codebase

**Comment by enitrat** [comment]
> > yes, this is the package where you define the cairo code, and you refer to it in the corpus using include macros (as done for other listings)
> 
> Good, can you refer me to where corpus was used in the codebase  @enitrat 

Look for the markdown file with the chapter name under src/

**Comment by mubarak23** [comment]
@enitrat do i need to add the remaining part of the content  from "[Submodules in Integration Tests](https://doc.rust-lang.org/book/ch11-03-test-organization.html#submodules-in-integration-tests)" downward

**Comment by okhaimie-dev** [comment]
@enitrat @TAdev0 

I'll take on this task
