### ISSUE TITLE
Building Advanced Contracts: price feeds section

### ISSUE THREAD

**Issue by TAdev0** [cairo-book/cairo-book#798]
Create a subsection in "Building Advanced Contracts', providing a contract example requesting a price feed using Pragma oracle. The contract should integrate the price feed in some way that makes sense. A good reference for how to do it properly is the VRF section with the example of the dice game

**Comment by fishonamos** [comment]
Kindly assign @TAdev0

**Comment by okhaimie-dev** [comment]
@TAdev0 @enitrat  I will like to work on this. I've spent enough time working with Pragma and I should be able to do this faster than the last

**Comment by TAdev0** [comment]
hi @okhaimie-dev  any update on this?

**Comment by okhaimie-dev** [comment]
I will make a PR today
