### ISSUE TITLE
fix: add missing derivable traits

### ISSUE THREAD

**Issue by milancermak** [cairo-book/cairo-book#818]
I've noticed there are 2 traits missing in the [Derivable traits](https://book.cairo-lang.org/appendix-03-derivable-traits.html) section:

* the `Default` trait
* the `starknet::Store` trait - I know the section is pure Cairo and the trait itself is Starknet specific, but I think it should be included there as the section is a handy reference of all the derivable traits (and let's be honest, Cairo is 95% Starknet so far)

**Comment by milancermak** [comment]
Can open a PR if I'm deemed worthy

**Comment by enitrat** [comment]
sure go ahead please 🙏
