### ISSUE TITLE
Running code in Listing 8-2 results in error "Negative impls are not enabled in the current crate"

### ISSUE THREAD

**Issue by 0xNeshi** [cairo-book/cairo-book#820]
Repro steps:
- open https://book.cairo-lang.org/ch08-02-traits-in-cairo.html#negative-impls
- find Listing 8-2
- click "Run this code"
- error appears

**Comment by enitrat** [comment]
hey @cryptonerdcn, do you think this can be supported by WASM-Cairo ?

**Comment by cryptonerdcn** [comment]
@enitrat I think it is possible. Let me try it.

**Comment by TAdev0** [comment]
@cryptonerdcn  could you find your way for supporting this?

**Comment by cryptonerdcn** [comment]
> @cryptonerdcn could you find your way for supporting this?

Yes please waiting for the next version.
