### ISSUE TITLE
Add information about triple slash (`///`) comments and their purpose

### ISSUE THREAD

**Issue by misicnenad** [cairo-book/cairo-book#830]
Triple slash comments (`/// some comment`) seem to be supported in Cairo, but there's no info in the book about them.
(Maybe I'm missing something?)

There should be at least a mention of these comments in the ["Comments"](https://book.cairo-lang.org/ch02-04-comments.html) chapter.

**Comment by enitrat** [comment]
For now they're useless as there is not documentation tool that can use them, but there will be in the future

**Comment by misicnenad** [comment]
Created an issue to make good use of these /// comments: https://github.com/starkware-libs/cairo/issues/5711

**Comment by enitrat** [comment]
I think the plan is for them to be equivalent to rust's `///`

**Comment by misicnenad** [comment]
I'll double check with the development team and post their response.

**Comment by misicnenad** [comment]
@enitrat there seems to be a plan to support at least 3 types of comments inspired by Rust:
- `//` - line comments
- `///` - contract-element documentation
- `//!` - contract documentation

All 3 types are supported atm in Cairo, compiler doesn't complain.

Taken from https://github.com/andrew-fleming/SNIPs/blob/comment-snip/SNIPS/snip-8.md

Also see: https://community.starknet.io/t/revisiting-the-comment-standard-natspec-or-rust/98009

**Comment by enitrat** [comment]
More generically,

// - line comments
/// - item-lvel documentation, used to document the item right after
//! - module-level documentation,  used to document the item it is present inside

**Comment by misicnenad** [comment]
Ah, understood. Do you think the latter 2 comment types should then be mentioned at all, given they are not yet supported by any 3rd party tool?

Maybe add docs on them once tooling exists?

**Comment by misicnenad** [comment]
@enitrat just checking in to see whether this is still something we want to implement or not?
See my previous message https://github.com/cairo-book/cairo-book/issues/830#issuecomment-2147686930

**Comment by enitrat** [comment]
Yes this can be a dedicated paragraph in https://book.cairo-lang.org/ch02-04-comments.html
