### ISSUE TITLE
feat: add section about defining custom type casts with `Into` and `TryInto` traits

### ISSUE THREAD

**Issue by misicnenad** [cairo-book/cairo-book#844]
Maybe add this to [Advanced Features](https://book.cairo-lang.org/ch11-00-advanced-features.html#advanced-features) section @enitrat @TAdev0 ?

**Comment by enitrat** [comment]
Can you specify what you have in mind exactly?

**Comment by misicnenad** [comment]
Will paste the example I'm working on for the Cairo track on Exercism:
```rust
pub struct Roman {
    value: ByteArray,
}

#[generate_trait]
impl RomanImpl of RomanTrait {
    fn new(num: u32) -> Roman {
        let mut ROMAN_MAP: Array<(u32, ByteArray)> = array![
            (1000, "M"),
            (900, "CM"),
            (500, "D"),
            (400, "CD"),
            (100, "C"),
            (90, "XC"),
            (50, "L"),
            (40, "XL"),
            (10, "X"),
            (9, "IX"),
            (5, "V"),
            (4, "IV"),
            (1, "I"),
        ];

        let mut value: ByteArray = "";
        let mut current_num = num;
        while let Option::Some((numeric, roman_string)) = ROMAN_MAP
            .pop_front() {
                while current_num >= numeric {
                    value.append(@roman_string);
                    current_num -= numeric;
                }
            };

        Roman { value }
    }
}

impl U32IntoRoman of Into<u32, Roman> {
    #[must_use]
    fn into(self: u32) -> Roman {
        RomanImpl::new(self)
    }
}
```

The last `impl` is what's important - it would be helpful for learners to know that they can define custom type casts from any custom type to any other by simply implementing the `Into` or `TryInto` traits.

**Comment by TAdev0** [comment]
do we really need it?

i think we mentioned that `try_into` trait returns an `option<T>`, which means its a trait with a generic type that can be implemented for any type? you think it lacks of clarity?

**Comment by misicnenad** [comment]
I still think it would be beneficial to show at least a simple example of implementing one of these traits for a custom type.

I try to assume that my experience can be shared by other people - and my experience was that even after reading The Cairo Book, I did not know I can define custom casts until I saw it implemented somewhere (I think it was Cairo corelib), and when I tried implementing it myself, I couldn't find any easily available resource on how to do that (in the end remembered I can reference the corelib to see how it can be used).

**Comment by TAdev0** [comment]
well in this case lets do this , @enitrat  what do you think?

**Comment by enitrat** [comment]
Ok, perhaps something similar to [https://doc.rust-lang.org/rust-by-example/conversion.html](Conversions).

Let's have this under `Advanced Cairo Features` until the need for more structure emerges

**Comment by misicnenad** [comment]
Hey @PedroRosalba , I was already working on a PR, was just wrapping it up.
