### ISSUE TITLE
feat: Arithmetic circuits section

### ISSUE THREAD

**Issue by julio4** [cairo-book/cairo-book#849]
Blocked until cairo v2.7.0 release

Section on how to define and evaluate circuits:
- `CircuitElement`
- `CircuitInput`
- Circuit operations: addition, substraction, multiplication, inversion
- `CircuitModulus`
- `u384`, how to set inputs, get output

See [circuit_test.cairo](https://github.com/starkware-libs/cairo/blob/main/corelib/src/test/circuit_test.cairo)

**Comment by julio4** [comment]
> Release post should be on monday

Nice to know! We can wait until then to start documenting 2.7 features then

**Comment by quentin-abei** [comment]
@julio4 , @enitrat  i would want to work on this

**Comment by enitrat** [comment]
up @julio4 is this something you will do? example use: https://github.com/kkrt-labs/kakarot-ssj/blob/6d60b97b1a503379447b791d4f012515b34d548b/crates/evm/src/precompiles/ec_add.cairo#L4

**Comment by julio4** [comment]
> up @julio4 is this something you will do? example use: https://github.com/kkrt-labs/kakarot-ssj/blob/6d60b97b1a503379447b791d4f012515b34d548b/crates/evm/src/precompiles/ec_add.cairo#L4

Picking this up now
