### ISSUE TITLE
dev: update starknet-foundry section to 2.7.0

### ISSUE THREAD

**Issue by enitrat** [cairo-book/cairo-book#864]
The compiler generated `<storage_var_name>ContractMemberStateTrait` traits, where `storage_var_name` is a name of a property of the `Storage` struct, no longer exist. Adapt the example so that it compiles with 2.7.0

**Comment by TAdev0** [comment]
@enitrat  I guess i should modify all Cairo contracts, not only the starknet foundry section ?

any contract now fails for `read` and `write` methods on `StorageBase` type, i guess the text of the storage section should also be modified

**Comment by enitrat** [comment]
> any contract now fails for read and write methods on StorageBase type, i guess the text of the storage section should also be modified

what do you mean? everything passes CI. are your scarb binaries up to date?
