### ISSUE TITLE
docs: update explanation on legacy map entries access

### ISSUE THREAD

**Issue by enitrat** [cairo-book/cairo-book#877]
see change from release 2.7: https://github.com/cairo-book/cairo-book/pull/876/files#diff-f047a06659d1cf05314b1480b35ce835a22563e431b8a8609a57459e92992196R67

Adapt the explanation in the contract storage page to match these.
Also, calling `storage_var.address()` is no longer possible - we can however call `storage_var.address` which returns a `felt252` - adapt accordingly

**Comment by blocksorcerer** [comment]
Hey @enitrat I would like to work on this!

**Comment by enitrat** [comment]
@blocksorcerer the book was updated to 2.7, you can start now. Please finish by tuesday (it should not take more than 30 mins)

**Comment by blocksorcerer** [comment]
Hey ser @enitrat ! Should I change `LegacyMap` to `Map` for 2.7 or just write explanation for current commit you've made?

**Comment by enitrat** [comment]
Just write the explanation relative to the commit linked, LegacyMap -> Map is for another issue! Just make sure that the text that comes with the code snippets is correct.
