### ISSUE TITLE
feat: macros with scarb

### ISSUE THREAD

**Issue by enitrat** [cairo-book/cairo-book#884]
scope: 0.75 day

https://x.com/swmansionxyz/status/1815343318529933421?t=e15zu78w0ZgaAgGMAlSzog&s=19

**Comment by okhaimie-dev** [comment]
@enitrat can I work on this once it is unblocked?

**Comment by okhaimie-dev** [comment]
this should be unblocked now. i'll get to it in a bit

re: https://github.com/software-mansion/scarb/releases

**Comment by enitrat** [comment]
@okhaimie-dev i actually think it would be better for software mansion to write it. Although you can give it a try if you'd like

**Comment by enitrat** [comment]
https://docs.swmansion.com/scarb/docs/reference/procedural-macro.html

**Comment by enitrat** [comment]
be careful: the page will not be a documentation of procedural macros, and must follow the tone of the book and approach of other chapters (what you did with pragma was good - but for this you will also need to focus on the core concept)

**Comment by enitrat** [comment]
@okhaimie-dev how are things going?

**Comment by okhaimie-dev** [comment]
got occupied with the dojo fellowship. I'll make a PR in about 48hrs. @enitrat
