### ISSUE TITLE
feat: individual storage member access

### ISSUE THREAD

**Issue by enitrat** [cairo-book/cairo-book#885]
We can now read individual members of structs in storage instead of loading the whole struct in memory and then accessing a member.

https://community.starknet.io/t/cairo-v2-7-0-is-coming/114362#individual-member-access-6

- Update the [example contract](https://book.cairo-lang.org/ch14-00-building-starknet-smart-contracts.html) to add a functionality related to the feature introduced (e.g. instead of getting the entire Person struct, return only the address)
- Update the Storage page to demonstrate how to read specific members of storage structs

The content created will need to be written in the same tone, format, and follow the guidelines of the rest of the book.

**Comment by Symmaque** [comment]
I can work on this

**Comment by quentin-abei** [comment]
@Symmaque , I can see you are working on 3 issues already . I’am happy to help if you want with this one.

**Comment by enitrat** [comment]
waiting for https://github.com/starkware-libs/cairo/issues/6067
