### ISSUE TITLE
feat(cairo-listings): add a sub-command to format listings

### ISSUE THREAD

**Issue by enitrat** [cairo-book/cairo-book#887]
`cairo-listings` has two commands: 
- `verify` to check that all code snippets are well formatted, and that build / tests pass properly
- `output` to run all snippets in which an `output.txt` file is defined, and save the output.

Add a third subcommand `format` that will format all listings using the same TAG rules as `verify`. Most of the logic is already implemented in the rust code. It should be doable in under an hour.

**Comment by okhaimie-dev** [comment]
@enitrat can you assign this to me? I'll take care of it when I wake up this morning

**Comment by enitrat** [comment]
@okhaimie-dev thanks for the heads up!
