### ISSUE TITLE
Help in adding CairoVM  documentation

### ISSUE THREAD

**Issue by gerceboss** [cairo-book/cairo-book#888]
I am new to Cairo and Starknet , I have not studied CairoVM in depth, was looking forward to doing that, so if it's possible I would like to help in writing the cairoVM documentation in the book, in that way I will study it as well and can help.

**Comment by enitrat** [comment]
Great idea :) it's probably good to start by reading https://github.com/kkrt-labs/cairo-vm-ts and https://github.com/lambdaclass/cairo-vm

**Comment by gerceboss** [comment]
Thanks a lot, is there any place where I can directly talk to people involved in this?

**Comment by enitrat** [comment]
You can find reference links in the Repo I linked, otherwise you can read the Cairo whitepaper

**Comment by gerceboss** [comment]
Great, np. Can you tell whom to contact while writing content for the book? It should be discussed as this might not be a small task.

**Comment by enitrat** [comment]
you can contact me directly. @zmalatrax wrote the cairo vm in typescript, @TAdev0 wrote it in Go, while I can help the overall writing direction and quality

**Comment by gerceboss** [comment]
@enitrat , I have completed reading the research paper of cairoVM/ cairo. Can I start writing? Or I should understand the implementations first?  And if yes, how should sections and everything needs to be structured , can you guide on that ?

**Comment by enitrat** [comment]
@gerceboss you can start writing the introduction if you want. Note that this work is the one of a technical writer, but it's not simply a documentation: there must be a "common thread" that guides the reader through the chapters.

We can discuss the content before writing, if you'd like.

**Comment by TAdev0** [comment]
@gerceboss  i'm closing this issue, feel free to look at #908  and open an issue if you want to write a specific chapter for the Cairo VM sub book
