### ISSUE TITLE
feat: Deref coercion

### ISSUE THREAD

**Issue by enitrat** [cairo-book/cairo-book#890]
The mechanism is similar to Rust's, but the scope is a lot smaller: trivially allow access to a member of T holding a type U.
https://doc.rust-lang.org/book/ch15-02-deref.html#treating-a-type-like-a-reference-by-implementing-the-deref-trait

Should go in 11. Advanced Features
Demonstration here: compile and read the casm to see what's happening
```
#[derive(Copy, Drop)]
struct MyStruct {
    x: felt252,
    y: felt252,
    z: felt252,
}

impl DerefType1ToType2 of Deref<Box<MyStruct>> {
    type Target = MyStruct;
    fn deref(self: Box<MyStruct>) -> Self::Target {
        let unboxed = self.unbox();
        Self::Target { x: unboxed.x, y: unboxed.y, z: unboxed.z }
    }
}


fn main() {
    let my_struct = MyStruct { x: 1, y: 2, z: 3 };
    let boxed = BoxTrait::new(my_struct);

    foo(boxed);
    bar(boxed);
}

#[inline(never)]
fn foo(boxed: Box<MyStruct>) -> felt252 {
    boxed.x
}

#[inline(never)]
fn bar(boxed: Box<MyStruct>) -> felt252 {
    boxed.unbox().x
}
```

**Comment by blocksorcerer** [comment]
Hi @enitrat I would like to work on this

**Comment by blocksorcerer** [comment]
@enitrat , Could you look at the PR and suggest possible changes as the build is failing.
