### ISSUE TITLE
feat: storage nodes

### ISSUE THREAD

**Issue by enitrat** [cairo-book/cairo-book#891]
Blend an explanation of storage nodes inside the Contract Storage section

https://community.starknet.io/t/cairo-v2-7-0-is-coming/114362#storage-nodes-12

They are really strong compared to the restrictions we had on storage before: now, we can have storage maps or storage vecs inside structs marked as storage nodes, which means that the architecture of a contract can be greatly simplified.

**Comment by blocksorcerer** [comment]
@enitrat, I can work on this.

**Comment by enitrat** [comment]
#916
