### ISSUE TITLE
feat: section on namespace & visibility

### ISSUE THREAD

**Issue by okhaimie-dev** [cairo-book/cairo-book#896]
we should include a section in the cairobook to go over how visibility works in Cairo. I am currently teaching a basecamp on Cairolang, and it gets a bit confusing to explain this to new devs.

ref: https://doc.rust-lang.org/reference/names.html

I am happy to work on this

**Comment by enitrat** [comment]
It already exists https://book.cairo-lang.org/ch07-03-paths-for-referring-to-an-item-in-the-module-tree.html#exposing-paths-with-the-pub-keyword
