### ISSUE TITLE
chore: bump `2.7.0-rc.3` to `2.7.0`

### ISSUE THREAD

**Issue by enitrat** [cairo-book/cairo-book#900]
Update all starknet dependencies and scarb versions to `2.7.0`

https://github.com/starkware-libs/cairo/releases/tag/v2.7.0

as soon as scarb releases 2.7

https://github.com/software-mansion/scarb/releases

-> simply find and replace all

**Comment by supreme2580** [comment]
Hi can I be assigned to this?
