### ISSUE TITLE
feat: add Cairo VM Implementations

### ISSUE THREAD

**Issue by zmalatrax** [cairo-book/cairo-book#912]
- List the different implementations of the Cairo VM that exist and their author (Python, Rust, Go, Zig, TypeScript, AppScript (google sheets)...)
- Precise in which state each project is (active/dead, in production/in development)
- Discuss the utility of having multiple implementations of the same software (e.g. Different goals: performance, clarity, ease of use: fast prototyping, integration into a tech stack...)

**Comment by zmalatrax** [comment]
@gerceboss

**Comment by quentin-abei** [comment]
Hello @zmalatrax  can I take this issue ?

**Comment by enitrat** [comment]
@gerceboss is on it already

**Comment by gerceboss** [comment]
@enitrat, I might be busy in upcoming days. Might not be able to spare enough time for the book. You can assign the issue to any other person.

**Comment by prix0007** [comment]
Hey @enitrat , Is this issue still up, I can take this up

**Comment by 0xNeshi** [comment]
I have some spare time, and wanted to dive a bit deeper into Cairo VMs, would be interested in working on this

**Comment by enitrat** [comment]
hey!

@prix0007 -> You could add a third sub-section in https://book.cairo-lang.org/ch200-introduction.html#virtual-machine with details about the Python and the Rust Cairo VM (other ones are not used in prod, i'd rather not mention them. Keep this sucicnt and fit for an introduction chapter

@0xNeshi -> Great, let me know if there's specific topic you'd like to take while you dive deeper. There's a lot to be done on this topic, everything is still left to do. I'd prefer you take another one

**Comment by prix0007** [comment]
On it ser.
