### ISSUE TITLE
feat(cairo-listings): add option to generate the output of a specific package

### ISSUE THREAD

**Issue by enitrat** [cairo-book/cairo-book#920]
Add an option in the cairo-listings CLI tool, for the `output` subcommand, to only generate an output for a specific package, based on its name.

**Comment by supreme2580** [comment]
Hi @enitrat can I be assigned to this

**Comment by adrianvrj** [comment]
Hi is this open for contribution?
If so, can I work on it?

**Comment by supreme2580** [comment]
Hi @enitrat I believe this issue should be closed as I've already have a merged PR for this
