### ISSUE TITLE
rework: `Copy` trait explanation

### ISSUE THREAD

**Issue by enitrat** [cairo-book/cairo-book#923]
> The important thing to note here is that this is a completely free operation because variables are a Cairo abstraction only and because values in Cairo are always immutable.

This line is a bit confusing when it comes to explaining the Copy trait. The copy mechanism plays only when interacting with functions: a value is either _moved_ or _copied_ (or snapped!).

In Rust, copy is a bit different: 
```rust
let x: i32 = 1;
let y:i32 = x;
```

This will allocate 8 bits of memory for both x and y. _Conceptually_, in Cairo, this would only allocate one cell, `x` and `y` being "labels" to this cell. In reality, it's up to the compiler to determine how x and y might be used later and figure out what to do with memory, as Cairo is a high level language. Unless x and y are consumed by something else (a computation, a function...) no memory would even be alocated.

All in all, copy is more of a guardrail mechanism that ensures a value owns no mutable memory, and is thus safe to use without moving it. And the only types in Cairo that do own mutable memory are Dicts and Arrays.

**Comment by FriendlyLifeguard** [comment]
Can I take this?
