### ISSUE TITLE
feat(theme): use cairo-specific highlighting

### ISSUE THREAD

**Issue by enitrat** [cairo-book/cairo-book#929]
Currently we highlight using Rust's syntax. Let's use Cairo's syntax highlighting available here
https://github.com/software-mansion/scarb/commit/41bb6ae0e8da269e3f6b74b534c258a402fe5e0a

- Register the cairo language in the highlight file
- Find-all-and-replace \`\`\`rust -> \`\`\`cairo

edit: blocked until https://github.com/software-mansion/scarb/issues/1565

**Comment by ShantelPeters** [comment]
Please can I work on this ?

**Comment by martinvibes** [comment]
hello@enitrat i will love to work on this

**Comment by ShantelPeters** [comment]
Thank you.. I’ll start working on it..

**Comment by enitrat** [comment]
Hi @ShantelPeters, I've seen you asking for assignment on other issues. If you are not working on this, please let me know and I will unassign you.

**Comment by ShantelPeters** [comment]
Hi @enitrat i am currently working on my issue already

**Comment by ShantelPeters** [comment]
hello @enitrat if i'm not mistaken i'm suppose to copy [this highlight.js](https://github.com/cairo-book/cairo-book/blob/main/theme/highlight.js) to [this](https://github.com/software-mansion/scarb/blob/main/extensions/scarb-doc/theme/highlight.js)

**Comment by enitrat** [comment]
you need to add syntax highlighting for Cairo by modifying the highlight file yes
