### ISSUE TITLE
Smart Contracts Section missing library imports (aka `use XXXX`)

### ISSUE THREAD

**Issue by sadikekin** [cairo-book/cairo-book#930]
I don't have the exact list. However i encountered this on the `Maps` (contract-storage) section. I needed to import `use starknet::storage::Map;` before using it in the storage section. Maybe it makes sense to do a proof read on that section in order to add the import statements.

**Comment by ShantelPeters** [comment]
Hi @sadikekin please can I work on this issue ?

**Comment by enitrat** [comment]
Hi @sadikekin do you have any specific example? As far as I've seen all examples that use a `Map` in storage have the import from `core::starknet::storage`.

**Comment by sadikekin** [comment]
Here: https://book.cairo-lang.org/ch14-01-contract-storage.html?highlight=map#storage-mappings

this was link i was checking when i write my contract. There were no mention about `core::starknet::storage`. Other links have it tho. So maybe adding specifically to that page also makes sense if an user doesn't check the other pages

**Comment by enitrat** [comment]
I see, thanks, indeed this snippet should be expandable, and you would be able to see the import (which is defined in the file)
