### ISSUE TITLE
feat: add new quiz / update quiz in control flow section

### ISSUE THREAD

**Issue by TAdev0** [cairo-book/cairo-book#948]
Currently, there are 3 out of 4 quiz in control flow related to if/else conditions, only one regarding loops, a bit outdated now there are `for` loops

Would be nice to add one or 2 more quizz to cover these new features +/- update the 4th quiz

**Comment by Jeanmichel7** [comment]
I'm interested, can I be assigned?

**Comment by Kishore-MK** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/the-cairo-book).

### My background and how it can be leveraged
I've been a web2 developer for quite some time and have been exploring web3 for about a year now. I'm have solid experience in Solidity and have been working with Cairo over the past three months. I've participated in starkhack and attended the starkhack buildstation during the hackathon, gaining valuable experience, and I successfully built a 2D game using cairo and dojo.

### How I plan on tackling this issue
First, take a look at the current quiz setup and see how everything is structured like the question flow. Once I've got a good grasp on that, connect with the maintainer to clear up any details and set a timeline. Then, work on adding or updating the quiz content based on what’s needed.

**Comment by enitrat** [comment]
https://github.com/cairo-book/cairo-book/pull/960
