### ISSUE TITLE
refactor: "Memory"`Vec` now conflicts with "Storage" `Vec`

### ISSUE THREAD

**Issue by enitrat** [cairo-book/cairo-book#966]
The new `Vec` type is used in storage only. 
In the book we present how to use a Dict to simulate a dynamic, memory Vec that can be manipulated at will.

Perhaps we will need to rename it, or find another way to explicitly state the difference.

**Comment by petersdt** [comment]
hi @ enitrat can i be assigned this task if open for contribution

**Comment by martinvibes** [comment]
hey @enitrat I would love to work on this

**Comment by ShantelPeters** [comment]
Hi @enitrat i will like to work on this

**Comment by NueloSE** [comment]
@enitrat can i work on this ?

**Comment by enitrat** [comment]
24368ce89819d1cbb66514e125826ef73012af6c
