### ISSUE TITLE
refactor: page layouts in the Oracle section

### ISSUE THREAD

**Issue by enitrat** [cairo-book/cairo-book#967]
In the VRF and Price Feeds sections, the layout of the page is not done correctly.

Goal:
- Improved Hierarchy: A clear, logical structure with properly nested headings (H1 > H2 > H3) helps both readers and search engines understand the organization of content.
- Better User Experience: Grouping related information under two main sections makes the content more digestible and easier to navigate.
- SEO Optimization: Search engines use heading structure to understand content relevance and importance. A well-structured page can potentially rank better.

```
# Price Feeds

## Setting Up Your Contract for Price Feeds
### Add Pragma as a Project Dependency
### Define the Contract Interface
### Import Pragma Dependencies
### Implement the Price Feed Function

## Example Application Using Pragma Price Feed
```

Apply the same reasoning to the VRF Page. Major topics should be under H2 headings, H3 and under for less important parts.

https://book.cairo-lang.org/ch16-05-02-randomness.html

**Comment by NueloSE** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/the-cairo-book).

### My background and how it can be leveraged
Hi 

### How I plan on tackling this issue
Can I work on this

**Comment by petersdt** [comment]
hi @enitrat can i be assigned this issue

**Comment by martinvibes** [comment]
hello @enitrat I would love to take on this issue if you allow me :)
