### ISSUE TITLE
deprecate using cairo-test for gas benchmarks

### ISSUE THREAD

**Issue by enitrat** [cairo-book/cairo-book#992]
https://book.cairo-lang.org/ch10-01-how-to-write-tests.html#benchmarking-the-gas-usage-of-a-specific-operation

This section should be deprecated in favor of starknet-foundry

**Comment by Kaminar-i** [comment]
hello @enitrat can i work on this

**Comment by TAdev0** [comment]
Hi @Kaminar-i  , thanks for your interest! Do you have any previous experience with Cairo and Starknet Foundry?

**Comment by omsant02** [comment]
i would like to take this issue

i have experience in Cairo, Starknet 
i have built application using Scaffold-Stark and were Finalists in Starknet's Buidl Camp

**Comment by TAdev0** [comment]
@omsant02  I'll work on it finally, thanks for your interest tho
