### ISSUE TITLE
Mention that formatting can be skipped per line using `#[cairofmt::skip]`

### ISSUE THREAD

**Issue by 0xNeshi** [cairo-book/cairo-book#993]
Page to update:
https://book.cairo-lang.org/appendix-06-useful-development-tools.html

This is a very useful thing to know, especially when needing to custom format arrays for clarity, e.g. to represent some table like:

```rust
    #[cairofmt::skip]
    let table = array![
        "oxo",
        "xox",
        "oxo",
    ];
```

This was implemented with https://github.com/starkware-libs/cairo/issues/4159

**Comment by enitrat** [comment]
Great to know! Thank you, please add
