### ISSUE TITLE
chore: update all configuration files for tests listings to use snforge

### ISSUE THREAD

**Issue by TAdev0** [cairo-book/cairo-book#997]
As of Scarb 2.8.3, snforge is the recommended default test runner when creating a package with Scarb.

The content of the "How to Write Tests" chapter has been updated entirely in #996 to use snforge , but we still need to update our listings so that we can regenerate the output for listings that contain tests. "Test Organizations" test result prints also need to be updated for the one we get with Starknet Foundry.

1. Check all the listings that contain a test which result is printed in the book (essentiellement listings of "How to Write Tests" and "Test Organization" chapters, but also one listing in "Testing Smart Contracts")
2. Update the scarb.toml configuration file of these listings to stick to what `scarb new` command produces when choosing starknet foundry, potentially adding `assert_macros = "2.8.2"` as a dev dependency if necessary (usage of `assert_xx!` macros).
3. Use `cairo-listings` command to regenerate outputs for these listings
4. Use the outputs to print the result instead of raw prints.

**Comment by ShantelPeters** [comment]
Hi @TAdev0 please can I be assigned to this issue?

**Comment by TAdev0** [comment]
Hi @ShantelPeters  sure. Just assigned you. Please wait for #996  to be merged first.

**Comment by ShantelPeters** [comment]
> Hi @ShantelPeters sure. Just assigned you. Please wait for #996 to be merged first.

Okay sir 🫡

**Comment by enitrat** [comment]
@TAdev0 it should be as simple as definining 
in `Scarb.toml`
```
[scripts]
test = "snforge test"
```

**Comment by TAdev0** [comment]
@ShantelPeters  #996  has been merged, you can work on this issue :)

**Comment by ShantelPeters** [comment]
> @ShantelPeters #996 has been merged, you can work on this issue :)

Alright sir @TAdev0 i will get straight to it

**Comment by TAdev0** [comment]
hi @ShantelPeters  any update for this?

**Comment by ShantelPeters** [comment]
Yea sir I’m still on it 
Will push a PR soon @TAdev0

**Comment by ShantelPeters** [comment]
Hi @TAdev0 i just pushed a PR kindly review it sir

**Comment by ShantelPeters** [comment]
hi @TAdev0  i just pushed a new pr, please check
